user/models.py
from application import db
from utilities.common import utc_now_ts as now

class User(db.Document):
	username = db.StringField(db_field="u", required=True, unique=True)
	password = db.StringField(db_field="p", required=True)
	email = db.EmailField(db_field="e", required=True, unique=True)
	first_name = db.StringField(db_field="fn", max_length=50)
	last_name = db.StringField(db_field="ln", max_length=50)
	created = db.IntField(db_field="c", default=now())

	meta = {
		'indexes': ['username', 'email', '-created']
	}

user/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError

from user.models import User

class RegisterForm(FlaskForm):
	first_name = StringField('First Name', [validators.DataRequired()])
	last_name = StringField('Last Name', [validators.DataRequired()])
	email = EmailField('Email', [
		validators.DataRequired(),
		validators.Email()
		])
	username = StringField('Username', [
		validators.DataRequired(),
		validators.length(min=4, max=25)
		])
	password = PasswordField('New Password', [
		validators.DataRequired(),
		validators.EqualTo('confirm', message='Passwords must match'),
		validators.length(min=8, max=80)
		])
	confirm = PasswordField('Repeat Password')

	def validate_username(form, field):
		if User.objects.filter(username=field.data).first():
			raise ValidationError("Username already exists")

	def validate_email(form, field):
		if User.objects.filter(email=field.data).first():
			raise ValidationError("Email is already in use")


class LoginForm(FlaskForm):
	username = StringField('Username', [
		validators.DataRequired(),
		validators.length(min=4, max=25)
		])
	password = PasswordField('Password', [
		validators.DataRequired(),
		validators.length(min=8, max=80)
		])

user/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from user.forms import RegisterForm, LoginForm
from user.decorators import login_required

import bcrypt
from user.models import User

user_app = Blueprint('user_app', __name__)

@user_app.route('/login', methods=('GET', 'POST'))
def login():
	form = LoginForm()
	error = None
	if request.method == 'GET' and request.args.get('next'):
		session['next'] = request.args.get('next')

	if form.validate_on_submit():
		user = User.objects.filter(
			username = form.username.data
			).first()
		if user:
			if bcrypt.hashpw(form.password.data.encode('utf-8'), user.password.encode('utf-8')) == user.password.encode('utf-8'):
				session['username'] = form.username.data
				if 'next' in session:
					next = session.get('next')
					session.pop('next')
					return redirect(next)
				else:
					return render_template('home.html')
			else:
				user = None
		if not user:
			error = 'Incorrect credentials'
	return render_template('user/login.html', form=form, error=error)

@user_app.route('/logout', methods=('GET', 'POST'))
@login_required
def logout():
	session.pop('username')
	return redirect(url_for('user_app.login'))

@user_app.route('/register', methods=('GET', 'POST'))
def register():
	form = RegisterForm()
	if form.validate_on_submit():
		salt = bcrypt.gensalt()
		hashed_password = bcrypt.hashpw(form.password.data.encode('utf-8'), salt)
		user = User(
			username=form.username.data,
			password=hashed_password,
			email=form.email.data,
			first_name=form.first_name.data,
			last_name=form.last_name.data
			)
		user.save()
		return "User Registered"
	return render_template('user/register.html', form=form)

@user_app.route('/profile', methods=('GET', 'POST'))
@login_required
def profile():
	user = session['username']
	return render_template('user/profile.html', user=user)

@user_app.route('/un', methods=('GET', 'POST'))
def un():
	return render_template('untitled.html')

workflow/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for

from user.decorators import login_required

workflow_app = Blueprint('workflow_app', __name__)

@workflow_app.route('/workflow', methods=('GET', 'POST'))
@login_required
def workflow():
	return render_template('workflow/design.html')

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
	{{ field.label }} {{ field(**kwargs)|safe }}
	{% if field.errors %}
		<ul class="text-danger">
		{% for error in field.errors %}
			<li>{{ error }}</li>
		{% endfor %}
		</ul>
	{% endif %}
</div>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>
         GRAINS• {% block title %} {% endblock %}
      </title>
      <!--     Fonts and icons     -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
      <!-- CSS Files -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/nav-custom.css') }}"/>
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/styles.css') }}"/>
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/draggable.css') }}"/>
   </head>
   <body class="body-main">
      {% include 'navbar.html' %}
      <div class="container-fluid">
         <div class="row">
            {% include 'sidebar.html' %}
            <main role="main" class="col-md-9 top-buffer">
               <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                     {% block content %}
                     {% endblock %}
               </div>
            </main>
         </div>
      </div>
      <!--   Core JS Files   -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="{{ url_for('static', filename='assets/js/styles.js') }}"></script>
      <script src="https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js"></script>
      <script type="text/javascript" src="{{ url_for('static', filename='assets/js/workflow.js') }}"></script>
   </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}


<div class="col-md-offset-3 col-md-6">
	<h3>Home</h3>

	
</div>


{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg p-0">
   <a class="navbar-brand" href="#">
   <img alt="grains logo" width="130" height="45" src="{{ url_for('static', filename='assets/img/grains-logo.png') }}">
   </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
   </button>
   <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
         <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
         </form>
         <li class="nav-item">
            <a class="nav-link text-white" href="#">Have an issue?</a>
         </li>
         <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
            Dropdown
            <i class="tim-icons icon-single-02" aria-hidden="true"></i>
            </a>

            {% if session.username %}
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
               <a class="dropdown-item" href="#">Action</a>
               <a class="dropdown-item" href="{{ url_for('user_app.profile') }}">Profile</a>
               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="{{ url_for('user_app.logout') }}">Sign out</a>
            </div>
            
            {% else %}
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
               <a class="dropdown-item" href="#">Action</a>
               <a class="dropdown-item" href="{{ url_for('user_app.register') }}">Register</a>
               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="{{ url_for('user_app.login') }}">Login</a>
            </div>
            {% endif %}
         </li>
      </ul>
   </div>
</nav>

templates/sidebar.html
<div class="col-md-2 d-none d-md-block">
    <aside id="mySidenav" class="main_sidebar">
        <ul>
            <li>
                <i id="side-collapse" class="fa fa-chevron-left"></i>
                <a href="#"></a>
            </li>
            <li>
                <i class="fa fa-heart"></i>
                <a href="#">Health Monitor</a>
            </li>
            <li>
                <i class="fa fa-bell"></i>
                <a href="#">Alerts</a>
            </li>
            <li>
                <i class="fa fa-align-justify"></i>
                <a href="#">Listings</a>
            </li>
            <li>
                <i class="fa fa-refresh"></i>
                <a href="#">Auto Discovery</a>
            </li>
            <li>
                <i class="fa fa-bug"></i>
                <a href="#">Report Bug</a>
            </li>
            <li>
                <i class="fa fa-cogs"></i>
                <a href="#">Auto Process</a>
            </li>
            <li>
                <i class="fa fa-database"></i>
                <a href="#">Databases</a>
            </li>
            <li>
                <i class="fa fa-server"></i>
                <a href="#">Servers</a>
            </li>
            <li>
                <i class="fa fa-bar-chart"></i>
                <a href="#">Analytics</a>
            </li>
        </ul>
    </aside>
</div>

templates/untitled.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>
         GRAINS• {% block title %} {% endblock %}
      </title>
      <!--     Fonts and icons     -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
      <!-- CSS Files -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/nav-custom.css') }}"/>
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/styles.css') }}"/>
      <style type="text/css">
.login-container{
    position: relative;
    width: 300px;
    margin: 80px auto;
    padding: 20px 40px 40px;
    text-align: center;
    background: #fff;
    border: 1px solid #ccc;
}

.login-container::before,.login-container::after{
    content: "";
    position: absolute;
    width: 100%;height: 100%;
    top: 3.5px;left: 0;
    background: #fff;
    z-index: -1;
    -webkit-transform: rotateZ(4deg);
    -moz-transform: rotateZ(4deg);
    -ms-transform: rotateZ(4deg);
    border: 1px solid #ccc;

}

.login-container::after{
    top: 5px;
    z-index: -2;
    -webkit-transform: rotateZ(-2deg);
     -moz-transform: rotateZ(-2deg);
      -ms-transform: rotateZ(-2deg);

}

.avatar{
    width: 100px;height: 100px;
    margin: 10px auto 30px;
    border-radius: 100%;
    border: 2px solid #aaa;
    background-size: cover;
}

.form-box input{
    width: 100%;
    padding: 10px;
    text-align: center;
    height:40px;
    border: 1px solid #ccc;;
    background: #fafafa;
    transition:0.2s ease-in-out;

}

.form-box input:focus{
    outline: 0;
    background: #eee;
}

.form-box input[type="text"]{
    border-radius: 5px 5px 0 0;
    text-transform: lowercase;
}

.form-box input[type="password"]{
    border-radius: 0 0 5px 5px;
    border-top: 0;
}

.form-box button.login{
    margin-top:15px;
    padding: 10px 20px;
}
      </style>
   </head>
   <body class="body-main">
      {% include 'navbar.html' %}
        <div class="container-fluid">
            <div class="login-container">
                <div id="output"></div>
                <div class="avatar"></div>
                <div class="form-box">
                    {% if error %}
                        <div class="error text-danger">{{ error }}</div>
                    {% endif %}

                    {% from "_formhelpers.html" import render_field %}
                    <form method="POST" action="{{ url_for('.login') }}" role="form">

                        {{ form.hidden_tag() }}
                        {{ render_field(form.username, class='form-control') }}
                        {{ render_field(form.password, class='form_control') }}

                        <button type="submit" class="btn btn-info btn-block login">Login</button>
                    </form>
                    <!--
                    <form action="" method="">
                        <input name="user" type="text" placeholder="username">
                        <input type="password" placeholder="password">
                        <button class="btn btn-info btn-block login" type="submit">Login</button>
                    </form>
                    -->
                </div>
            </div>
        </div>
      </div>
      <!--   Core JS Files   -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   </body>
</html>

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>
         GRAINS• {% block title %} {% endblock %}
      </title>
      <!--     Fonts and icons     -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
      <!-- CSS Files -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/nav-custom.css') }}"/>
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/styles.css') }}"/>
   </head>
   <body class="body-main">
      {% include 'navbar.html' %}
        <div class="container-fluid">
            <div class="login-container">
                <div id="output"></div>
                <div class="avatar">
                   <img width="100" height="100" src="{{ url_for('static', filename='assets/img/icon.png') }}">
                </div>
                <div class="form-box">
                    {% if error %}
                        <div class="error text-danger">{{ error }}</div>
                    {% endif %}

                    {% from "_formhelpers.html" import render_field %}
                    <form method="POST" action="{{ url_for('.login') }}" role="form">

                        {{ form.hidden_tag() }}
                        {{ render_field(form.username, class='form-control') }}
                        {{ render_field(form.password, class='form_control') }}

                        <button type="submit" class="btn btn-block login">Login</button>
                    </form>
                </div>
            </div>
        </div>
      </div>
      <!--   Core JS Files   -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   </body>
</html>

templates/user/profile.html
{% extends "base.html" %}

{% block title %}{{ user }} - Profile{% endblock %}

{% block content %}

<div class="col-md-offset-3 col-md-6">
	<h3>{{ user }} Profile</h3>

	
</div>


{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}


<div class="container-fluid">
    <div class="row justify-content-center align-items-center">
        <div class="col col-sm-6 col-md-6">
			<h3>Registration</h3>

			{% from "_formhelpers.html" import render_field %}
			<form method="POST" action="{{ url_for('user_app.register') }}" role="form">

				{{ form.hidden_tag() }}

				{{ render_field(form.first_name, class='form-control') }}
				{{ render_field(form.last_name, class='form-control') }}
				{{ render_field(form.username, class='form-control') }}
				{{ render_field(form.email, class='form-control') }}
				{{ render_field(form.password, class='form-control') }}
				{{ render_field(form.confirm, class='form-control') }}

				<button type="submit" class="btn btn-info btn-lg btn-block">Register</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/workflow/design.html
{% extends "base.html" %}

{% block title %}{{ user }} - Profile{% endblock %}

{% block content %}

<div class="col-md-offset-3 col-md-6">
	<div id="drag-1" class="draggable">
  		<p> You can drag one element </p>
	</div>
	<div id="drag-2" class="draggable">
  		<p> with each pointer </p>
	</div>

	
</div>


{% endblock %}